DROP USER VT_USER CASCADE;

CREATE USER VT_USER
  IDENTIFIED BY VT_USER
  DEFAULT TABLESPACE OFMP_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
ALTER USER VT_USER 
  QUOTA UNLIMITED 
  ON OFMP_DATA;

ALTER USER VT_USER 
  QUOTA UNLIMITED 
  ON OFMP_IDX;
/

exit