DROP USER VT_REPORT CASCADE;

CREATE USER VT_REPORT
  IDENTIFIED BY VT_REPORT
  DEFAULT TABLESPACE OFMP_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
ALTER USER VT_REPORT 
  QUOTA UNLIMITED 
  ON OFMP_DATA;

ALTER USER VT_REPORT 
  QUOTA UNLIMITED 
  ON OFMP_IDX;
/

exit