/*==============================================================*/
/* Role: VTUSER                                                 */
/*==============================================================*/

DROP ROLE VTUSER;

CREATE ROLE VTUSER NOT IDENTIFIED;

GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.ACCOUNTING_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.BACKOFFICE_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.BACKOFFICE_ERROR_MESSAGE TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.BACKOFFICE_SCHEDULE TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.BANK TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.COUNTERPARTY TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.CURRENCY TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.CURRENCY_RATES TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.CUSTOMER TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.OFMP_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.V_FX_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.V_MM_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.DEALER TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.DEALER_CODE TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.FORWARD_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.TOF_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.TOF_ERROR_MESSAGE TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.TOF_TICKET TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.ROLE TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.SPOT_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.SWAP_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.SWAP_FAR_LEG TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.SWAP_NEAR_LEG TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.USERS TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.BANK_CODE TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.HISTORY TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.HISTORY_CAUSE TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.PROFIT_LOSS TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.BUSINESS_DAY TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.LOAN_DEPOSIT_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.ATOMIC_POSITION TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.POSITION_CORRECTION TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.TRANSFER_DEAL TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.NOSTRO_ACCOUNT TO VTUSER;
GRANT DELETE, INSERT, SELECT, UPDATE ON  VT_OWNER.REFERENCE_POSITION TO VTUSER;


GRANT SELECT ON  VT_OWNER.USER_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.ROLE_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.HISTORY_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.PROFIT_LOSS_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.POSITION_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.ATOMIC_POSITION_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.POSITION_CORRECTION_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.REFERENCE_POSITION_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.TOF_ERROR_MESSAGE_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.DEAL_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.COUNTERPARTY_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.BACKOFFICE_ERROR_MESSAGE_SEQ TO VTUSER;
GRANT SELECT ON  VT_OWNER.NOSTRO_ACCOUNT_SEQ TO VTUSER;

GRANT CONNECT TO VTUSER;
GRANT CREATE TABLE TO VTUSER;

GRANT VTUSER TO VT_USER;

/*==============================================================*/
/* Role: VTREPORT                                               */
/*==============================================================*/

DROP ROLE VTREPORT;

CREATE ROLE VTREPORT NOT IDENTIFIED;

GRANT SELECT ON VT_OWNER.ACCOUNTING_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.BACKOFFICE_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.BACKOFFICE_ERROR_MESSAGE TO VTREPORT;
GRANT SELECT ON VT_OWNER.BACKOFFICE_SCHEDULE TO VTREPORT;
GRANT SELECT ON VT_OWNER.BANK TO VTREPORT;
GRANT SELECT ON VT_OWNER.COUNTERPARTY TO VTREPORT;
GRANT SELECT ON VT_OWNER.CURRENCY TO VTREPORT;
GRANT SELECT ON VT_OWNER.CURRENCY_RATES TO VTREPORT;
GRANT SELECT ON VT_OWNER.CUSTOMER TO VTREPORT;
GRANT SELECT ON VT_OWNER.OFMP_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.V_FX_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.V_MM_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.DEALER TO VTREPORT;
GRANT SELECT ON VT_OWNER.FORWARD_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.TOF_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.TOF_ERROR_MESSAGE TO VTREPORT;
GRANT SELECT ON VT_OWNER.TOF_TICKET TO VTREPORT;
GRANT SELECT ON VT_OWNER.ROLE TO VTREPORT;
GRANT SELECT ON VT_OWNER.SPOT_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.SWAP_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.SWAP_FAR_LEG TO VTREPORT;
GRANT SELECT ON VT_OWNER.SWAP_NEAR_LEG TO VTREPORT;
GRANT SELECT ON VT_OWNER.USERS TO VTREPORT;
GRANT SELECT ON VT_OWNER.BANK_CODE TO VTREPORT;
GRANT SELECT ON VT_OWNER.HISTORY TO VTREPORT;
GRANT SELECT ON VT_OWNER.HISTORY_CAUSE TO VTREPORT;
GRANT SELECT ON VT_OWNER.PROFIT_LOSS TO VTREPORT;
GRANT SELECT ON VT_OWNER.LOAN_DEPOSIT_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.ATOMIC_POSITION TO VTREPORT;
GRANT SELECT ON VT_OWNER.POSITION_CORRECTION TO VTREPORT;
GRANT SELECT ON VT_OWNER.TRANSFER_DEAL TO VTREPORT;
GRANT SELECT ON VT_OWNER.NOSTRO_ACCOUNT TO VTREPORT;
GRANT SELECT ON VT_OWNER.REFERENCE_POSITION TO VTREPORT;


GRANT SELECT ON VT_OWNER.TOF_ERROR_MESSAGE_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.DEAL_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.COUNTERPARTY_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.BACKOFFICE_ERROR_MESSAGE_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.USER_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.ROLE_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.HISTORY_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.PROFIT_LOSS_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.POSITION_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.POSITION_CORRECTION_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.REFERENCE_POSITION_SEQ TO VTREPORT;
GRANT SELECT ON VT_OWNER.NOSTRO_ACCOUNT_SEQ TO VTREPORT;

GRANT CONNECT TO VTREPORT;

GRANT VTREPORT TO VT_REPORT;
GRANT VTREPORT TO VT_OWNER;
/

exit